export const imagesSlider = [
    '/img/slider/anh_bia_card_lenti.jpg',
    '/img/slider/anh_bia_card_pvc-01-01.jpg',
    '/img/slider/card_C300.jpg',
    
];

export const products = [
    {
      link:'/card-giay-c300',
      name: "Card giấy C300",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Card bo góc",
      material:["Giấy C300"],
      effect:["Bóng", "Mờ", "Hologram", "Kim tuyến"],
      size:["6x9", "8.5x5.5", "5.4x8.6", "6x6", "9x5.4", "5x15"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Card cứng 4K",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Card bo góc",
      material:["Giấy cứng 4K"],
      effect:["Bóng", "Lụa", "Hologram", "Kim tuyến"],
      size:["6x9", "8.5x5.5", "5.4x8.6", "6x6", "9x5.4", "5x15"],

      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Card nhựa PVC",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      category:"Card bo góc",
      sides:"2 mặt",
      material:["Nhựa PVC"],
      effect:["non"],
      size:["6x9", "8.5x5.5", "5.4x8.6", "6x6", "9x5.4", "5x15"],

      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
        name: "Card Polar",
        name2:"Đáp ứng mọi số lượng",
        color:"Nhiều màu",
        colorsys:"CMYK",
        pritech:"In KTS",
        cut:"Theo khuôn chuẩn",
        category:"Card bo góc",
        sides:"1 mặt",
        material:["Polar"],
        effect:["non"],
        size:["6x9", "8.5x5.5", "5.4x8.6", "6x6", "9x5.4", "5x15"],

        price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
        love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
      },
    {
      name: "Card Lenti",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      category:"Card bo góc",
      sides:"2 mặt",
      material:["Lenti"],
      effect:["non"],
      size:["6x9", "8.5x5.5", "5.4x8.6", "6x6", "9x5.4", "5x15"],

      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Post card giấy C300",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Post card",
      material:["Giấy C300"],
      effect:["Bóng", "Mờ", "Hologram", "Kim tuyến"],
      size:["10x15", "10x18"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Post card Lenti",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Post card",
      material:["Lenti"],
      effect:["non"],
      size:["10x15", "10x18"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Photostrip giấy C300",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Photostrip",
      material:["Giấy C300"],
      effect:["Bóng", "Mờ", "Hologram", "Kim tuyến"],
      size:["5x15", "5x20"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      link:'/sticker',
      name: "Sách ảnh bìa cứng",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Sách ảnh bìa",
      material:["Bìa cứng"],
      effect:["non"],
      size:["20x30"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Sách ảnh bìa mềm",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Sách ảnh bìa",
      material:["Bìa mềm"],
      effect:["non"],
      size:["20x30"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Khung ảnh để bàn",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"1 mặt",
      category:"Khung ảnh",
      material:["Nhựa composit"],
      effect:["non"],
      size:["13x18", "20x30"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Khung ảnh treo tường",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"1 mặt",
      category:"Khung ảnh",
      material:["Nhựa composit"],
      effect:["non"],
      size:["30x40cm", "40x60cm", "60x90cm"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Lịch để bàn",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Lịch",
      material:["Giấy"],
      size:["non"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Sổ tay",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Sổ tay",
      material:["Giấy"],
      effect:["non"],
      size:["non"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Sticker",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo file thiết kế",
      sides:"1 mặt",
      category: "Sticker",
      material:["Bế Demi", "Cắt rời"],
      effect:["Bóng", "Mờ", "Hologram", "Kim tuyến"],
      size:["A3", "A5", "3x4cm/cái"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Poster A3",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"1 mặt",
      category:"Poster",
      material:["Mica", "Giấy", "Fomex"],
      effect:["Bóng", "Mờ", "Kim tuyến", "Hologram"],
      size:["20x30", "30x40", "40x60", "60x90"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Poster A2",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category:"Poster",
      material:["Mica", "Giấy", "Fomex"],
      effect:["Bóng", "Mờ", "Kim tuyến", "Hologram"],
      size:["20x30", "30x40", "40x60", "60x90"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
    {
      name: "Standee",
      name2:"Đáp ứng mọi số lượng",
      color:"Nhiều màu",
      colorsys:"CMYK",
      pritech:"In KTS",
      cut:"Theo khuôn chuẩn",
      sides:"2 mặt",
      category: "Standee",
      material:["Mica"],
      effect:["Bóng"],
      size:["80x50", "30x40"],
      price: `${(Math.random() * (2.0 - 0.5) + 0.5).toFixed(1)} k/cái`,
      love: `${(Math.random() * (3.0 - 0.5) + 0.5).toFixed(1)} k`
    },
  ];